name: Deploy to Vercel
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_e2UURpRdTFIf1yrpGTW252Q9
          vercel-project-id: prj_ARBBF6eI09ixTxP6KmTTlTU9c9Ax
          vercel-args: --prod
